<?php

use Illuminate\Database\Seeder;
use App\Model\Dish;
use Illuminate\Support\Str;

class DishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dishes = [
            [
                'name' => 'Margherita',
                'image' => 'margherita.jpg',
                'description' => 'Pomodoro, fior di latte e basilico',
                'price' => 4.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Marinara',
                'image' => 'marinara.jpg',
                'description' => 'Pomodoro, aglio, origano',
                'price' => 4.00,
                'visible' => 1,
                'vegan' => 1,
                'spicy' => 0,
                'user_id' => 1,
            ],
            [
                'name' => '4 Stagioni',
                'image' => '4stagioni.jpg',
                'description' => 'Pomodoro, fior di latte, salame, zucchine, funghi, prosciutto cotto, basilico',
                'price' => 6.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Ortolana',
                'image' => 'ortolana.jpg',
                'description' => 'Pomodoro, fior di latte, melanzane fritte, zucchine e funghi freschi',
                'price' => 6.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Doc',
                'image' => 'doc.jpg',
                'description' => 'Pomodorini datterini, mozzarella di bufala, basilico',
                'price' => 6.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Calabrese',
                'image' => 'calabrese.jpg',
                'description' => 'Pomodoro, fior di latte, salame, cipolla, peperoncino, basilico',
                'price' => 5.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Ischitana',
                'image' => 'ischitana.jpg',
                'description' => 'Pomodorini datterini, mozzarella di bufala, prosciutto crudo, rucola, scaglie di parmigiano',
                'price' => 8.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Salsiccia e friarielli',
                'image' => 'salsiccia_friarielli.jpg',
                'description' => 'Mozzarella, salsiccia a punta di coltello, friarielli',
                'price' => 6.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Siciliana',
                'image' => 'siciliana.jpg',
                'description' => 'Pomodoro, acciughe, origano, olive nere, capperi, basilico',
                'price' => 6.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Romana',
                'image' => 'romana.jpg',
                'description' => 'Pomodoro, fior di latte, acciughe, origano, basilico',
                'price' => 6.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Mondial',
                'image' => 'mondial.jpg',
                'description' => 'Fior di latte, pomodorini datterini, capperi, olive nere, origano, basilico',
                'price' => 6.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Lasagna',
                'image' => 'lasagna.jpg',
                'description' => 'Pomodoro, fior di latte, prosciutto cotto, ricotta, basilico',
                'price' => 6.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Cicolone',
                'image' => 'cicolone.jpg',
                'description' => 'Ombra di pomodoro, provola, ricotta, cicoli, pepe, basilico',
                'price' => 7.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Positano',
                'image' => 'positano.jpg',
                'description' => 'Fior di latte, gorgonzola, salame, cipolla, basilico',
                'price' => 7.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Big Joe',
                'image' => 'big_joe.jpg',
                'description' => "200 grammi di scottona, cheddar, bacon, pomodoro confit, salsa Jack Daniel's",
                'price' => 10.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 2,
            ],
            [
                'name' => 'Double',
                'image' => 'big_joe.jpg',
                'description' => "Formaggio cheddar 40 g, doppio beef burger 240 g, insalata, cipolla, pomodoro, e salsa burger",
                'price' => 12.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 2,
            ],
            [
                'name' => 'Triple',
                'image' => 'big_joe.jpg',
                'description' => "Formaggio cheddar 60 g, triplo beef burger 360 g, insalata, cipolla, pomodoro e salsa burger",
                'price' => 13.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 2,
            ],
            [
                'name' => 'Smoker',
                'image' => 'big_joe.jpg',
                'description' => "Hamburger di bovino scelto italiano, cheddar, bacon croccante, cipolla croccante, mayo al bacon - doppio burger e doppio cheddar",
                'price' => 10.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 2,
            ],
            [
                'name' => 'The Eggy',
                'image' => 'big_joe.jpg',
                'description' => "Hamburger di bovino scelto italiano, uovo all’occhio, bacon croccante, cheddar, salsa market burger - doppio hamburger e doppio cheddar",
                'price' => 10.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 2,
            ],
            [
                'name' => 'The Smiths',
                'image' => 'big_joe.jpg',
                'description' => "Pulled pork cotto a bassa temperatura e marinato alla birra, insalata coslow, fonduta blue stilton",
                'price' => 11.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 2,
            ],
            [
                'name' => 'Pollo\'s',
                'image' => 'big_joe.jpg',
                'description' => "Filetto di pollo fritto alla paprika affumicata, insalata verde, pomodoro, mayo al bacon, bacon croccante",
                'price' => 9.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 2,
            ],
            [
                'name' => 'Patate fritte',
                'image' => null,
                'description' => "Servite con salsa dedicata o mayonese vegan",
                'price' => 3.00,
                'visible' => 1,
                'vegan' => 1,
                'spicy' => 0,
                'user_id' => 2,
            ],
            [
                'name' => 'Patate dolci',
                'image' => null,
                'description' => "Servite con salsa dedicata o mayonese vegan",
                'price' => 3.50,
                'visible' => 1,
                'vegan' => 1,
                'spicy' => 0,
                'user_id' => 2,
            ],
            [
                'name' => 'Filetto di pollo fritto',
                'image' => 'big_joe.jpg',
                'description' => "Con salsa delicata (3 pz)",
                'price' => 4.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 2,
            ],
            [
                'name' => 'Fiori di zucca',
                'image' => 'big_joe.jpg',
                'description' => "Fiori di zucca pastellati (5 pz)",
                'price' => 4.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 2,
            ],
            [
                'name' => 'Spicy Wings',
                'image' => 'big_joe.jpg',
                'description' => "Alette di pollo fritte, guarnite con salsa asian BBQ, cipollotto e peperoncino dolce",
                'price' => 5.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 2,
            ],
            [
                'name' => 'Crispy rolls',
                'image' => 'big_joe.jpg',
                'description' => "Involtini di verdure e mazzancolle (5 pz)",
                'price' => 4.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 2,
            ],
            [
                'name' => 'Kraken',
                'image' => 'kraken.jpg',
                'description' => "pan brioche artigianale, 5 hamburger (750gr in totale) di scottona grass feed allevata esclusivamente a erba, 10 fette di bacon affumicato, 5 fette di cheddar inglese e maionese al bacon fatta in casa",
                'price' => 27.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 2,
            ],
            [
                'name' => 'Veggie burger',
                'image' => 'veggie_burger.jpg',
                'description' => "Hamburger di soia, pomodoro, lattuga, fungo fritto, maionese vegana",
                'price' => 13.00,
                'visible' => 1,
                'vegan' => 1,
                'spicy' => 0,
                'user_id' => 2,
            ],
            [
                'name' => 'Le alici di Annunziata',
                'image' => 'alici_annunziata.jpg',
                'description' => 'Puntarelle e colatura di alici',
                'price' => 8.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 3,
            ],
            [
                'name' => 'Rapid Vienna',
                'image' => 'alici_annunziata.jpg',
                'description' => 'Filetto di sgombro viennese',
                'price' => 11.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 3,
            ],
            [
                'name' => 'Sarde Frittur',
                'image' => 'frittura_pesce.jpg',
                'description' => 'Sarde fritte',
                'price' => 6.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 3,
            ],
            [
                'name' => 'Cozze Frittur',
                'image' => 'cozze.jpg',
                'description' => 'Cozze fritte',
                'price' => 8.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 3,
            ],
            [
                'name' => 'Misto Frittur',
                'image' => 'frittura_pesce.jpg',
                'description' => 'Calamari, seppia, gamberetti, gamberoni e canestrelli fritti',
                'price' => 12.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 3,
            ],
            [
                'name' => 'L\'Hamburger',
                'image' => 'veggie_burger.jpg',
                'description' => 'Hamburger di branzino al timo o di orata al rosmarino fatto a mano',
                'price' => 11.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 3,
            ],
            [
                'name' => 'Tonno Piastra',
                'image' => 'filetto_pesce.jpg',
                'description' => 'Filetto di tonno alla piastra',
                'price' => 11.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 3,
            ],
            [
                'name' => 'Filetti Mix',
                'image' => 'filetto_pesce.jpg',
                'description' => '2 a scelta tra: orata, sogliola, branzino',
                'price' => 11.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 3,
            ],
            [
                'name' => 'Salmone Piastra',
                'image' => 'filetto_pesce.jpg',
                'description' => 'Filetto di salmone alla piastra',
                'price' => 10.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 3,
            ],
            [
                'name' => 'Baccalà Mantecato',
                'image' => 'filetto_pesce.jpg',
                'description' => 'Baccalà fritto',
                'price' => 8.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 3,
            ],
            [
                'name' => 'Baccalà Vibo',
                'image' => 'filetto_pesce.jpg',
                'description' => 'Baccalà in umido',
                'price' => 10.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 3,
            ],
            [
                'name' => 'Sarde in Saor',
                'image' => 'martinelli_lago.jpg',
                'description' => 'Puntarelle e colatura di alici',
                'price' => 5.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 3,
            ],
            [
                'name' => 'Mazzancolle in Saor',
                'image' => 'martinelli_lago.jpg',
                'description' => 'Puntarelle e colatura di alici',
                'price' => 8.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 3,
            ],
            [
                'name' => 'Spaghetti allo scoglio',
                'image' => 'spaghetti_scoglio.jpg',
                'description' => 'Spaghetti con misto pesce e crostacei',
                'price' => 13.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 3,
            ],
            [
                'name' => 'Martinelli di lago',
                'image' => 'martinelli_lago.jpg',
                'description' => 'Martinelli con carciofi e menta',
                'price' => 14.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 3,
            ],
            [
                'name' => 'Margherita',
                'image' => 'margherita.jpg',
                'description' => 'Pomodoro, fior di latte e basilico',
                'price' => 4.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 4,
            ],
            [
                'name' => 'Marinara',
                'image' => 'marinara.jpg',
                'description' => 'Pomodoro, aglio, origano',
                'price' => 4.00,
                'visible' => 1,
                'vegan' => 1,
                'spicy' => 0,
                'user_id' => 4,
            ],
            [
                'name' => '4 Stagioni',
                'image' => '4stagioni.jpg',
                'description' => 'Pomodoro, fior di latte, salame, zucchine, funghi, prosciutto cotto, basilico',
                'price' => 6.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 4,
            ],
            [
                'name' => 'Contadina',
                'image' => 'ortolana.jpg',
                'description' => 'Pomodoro, fior di latte, melanzane fritte, zucchine e funghi freschi',
                'price' => 6.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 4,
            ],
            [
                'name' => 'Doc',
                'image' => 'doc.jpg',
                'description' => 'Pomodorini datterini, mozzarella di bufala, basilico',
                'price' => 6.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 4,
            ],
            [
                'name' => 'Red Bone',
                'image' => 'calabrese.jpg',
                'description' => 'Pomodoro, fior di latte, salame, cipolla, peperoncino, basilico',
                'price' => 5.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 4,
            ],
            [
                'name' => 'Tonno alla Piastra',
                'image' => 'filetto_pesce.jpg',
                'description' => 'Filetto di tonno alla piastra',
                'price' => 11.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 4,
            ],
            [
                'name' => 'Misto di Filetti',
                'image' => 'filetto_pesce.jpg',
                'description' => '2 a scelta tra: orata, sogliola, branzino',
                'price' => 11.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 4,
            ],
            [
                'name' => 'Salmone alla Piastra',
                'image' => 'filetto_pesce.jpg',
                'description' => 'Filetto di salmone alla piastra',
                'price' => 10.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 4,
            ],
            [
                'name' => '\'A Mpepat\' e Cozz\'',
                'image' => 'cozze.jpg',
                'description' => '',
                'price' => 11.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 4,
            ],
            [
                'name' => 'Frittura Mista di Mare',
                'image' => 'frittura_pesce.jpg',
                'description' => 'Calamari, seppia, gamberetti, gamberoni e canestrelli fritti',
                'price' => 12.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 4,
            ],
            [
                'name' => 'Nigiri Salmon',
                'image' => 'nigiri.jpg',
                'description' => '',
                'price' => 3.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 5,
            ],
            [
                'name' => 'Nigiri Polpo',
                'image' => 'nigiri.jpg',
                'description' => '',
                'price' => 3.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 5,
            ],
            [
                'name' => 'Nigiri Tonno',
                'image' => 'nigiri.jpg',
                'description' => '',
                'price' => 4.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 5,
            ],
            [
                'name' => 'Nigiri Branzino',
                'image' => 'nigiri.jpg',
                'description' => '',
                'price' => 4.50,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 5,
            ],
            [
                'name' => 'Nigiri Gamberi',
                'image' => 'nigiri.jpg',
                'description' => '',
                'price' => 4.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 5,
            ],
            [
                'name' => 'Philadelphia Roll',
                'image' => 'rolls.jpg',
                'description' => '',
                'price' => 5.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 5,
            ],
            [
                'name' => 'California Roll',
                'image' => 'rolls.jpg',
                'description' => '',
                'price' => 5.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 5,
            ],
            [
                'name' => 'Avocado Roll',
                'image' => 'rolls.jpg',
                'description' => '',
                'price' => 5.00,
                'visible' => 1,
                'vegan' => 1,
                'spicy' => 0,
                'user_id' => 5,
            ],
            [
                'name' => 'Tuna Roll',
                'image' => 'rolls.jpg',
                'description' => '',
                'price' => 5.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 5,
            ],
            [
                'name' => 'Spicy Salmon Roll',
                'image' => 'rolls.jpg',
                'description' => '',
                'price' => 5.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 5,
            ],
            [
                'name' => 'Spaghetti di riso con verdure',
                'image' => 'udon.jpg',
                'description' => '',
                'price' => 4.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 5,
            ],
            [
                'name' => 'Spaghetti di riso con manzo',
                'image' => 'udon.jpg',
                'description' => '',
                'price' => 5.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 5,
            ],
            [
                'name' => 'Spaghetti di soia con verdure',
                'image' => 'udon.jpg',
                'description' => '',
                'price' => 4.00,
                'visible' => 1,
                'vegan' => 1,
                'spicy' => 0,
                'user_id' => 5,
            ],
            [
                'name' => 'Spaghetti di riso con frutti di mare',
                'image' => 'udon.jpg',
                'description' => '',
                'price' => 5.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 5,
            ],
            [
                'name' => 'Spaghetti di riso con gamberi',
                'image' => 'udon.jpg',
                'description' => '',
                'price' => 4.00,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 5,
            ],
            [
                'name' => 'Bis di ciocco cocco',
                'image' => 'mochi.jpg',
                'description' => '2 Toy Mochi al gusto ciocco cocco',
                'price' => 6.40,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 6,
            ],
            [
                'name' => 'Bis di arachide',
                'image' => 'mochi.jpg',
                'description' => '2 Toy Mochi al gusto di arachidi',
                'price' => 6.40,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 6,
            ],
            [
                'name' => 'Bis di panna',
                'image' => 'mochi.jpg',
                'description' => '2 Toy Mochi al gusto panna',
                'price' => 6.40,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 6,
            ],
            [
                'name' => 'Bis di cioccolato',
                'image' => 'mochi.jpg',
                'description' => '2 Toy Mochi al gusto cioccolato',
                'price' => 6.40,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 6,
            ],
            [
                'name' => 'Bis di the matcha',
                'image' => 'mochi.jpg',
                'description' => '2 Toy Mochi al gusto the matcha',
                'price' => 6.40,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 6,
            ],
            [
                'name' => 'Bis di pistacchio di Bronte',
                'image' => 'mochi.jpg',
                'description' => '2 Toy Mochi al pistacchio di Bronte',
                'price' => 6.40,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 6,
            ],
            [
                'name' => 'La Riccia',
                'image' => 'pasticceria.jpg',
                'description' => 'Sfogliatella riccia di Peppe',
                'price' => 2.40,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 6,
            ],
            [
                'name' => 'La Frolla',
                'image' => 'pasticceria.jpg',
                'description' => 'Sfogliatella frolla di Peppe',
                'price' => 2.40,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 6,
            ],
            [
                'name' => 'O\' Boss',
                'image' => 'pasticceria.jpg',
                'description' => 'Babà al rum',
                'price' => 2.40,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 6,
            ],
            [
                'name' => 'A\' Mamm',
                'image' => 'pasticceria.jpg',
                'description' => 'Pastiera napoletana',
                'price' => 3.40,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 6,
            ],
            [
                'name' => 'A\' Nonn',
                'image' => 'pasticceria.jpg',
                'description' => 'Caprese al cacao e zucchero a velo',
                'price' => 3.40,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 6,
            ],
            [
                'name' => 'Salmone poke',
                'image' => 'poke.jpg',
                'description' => 'Riso sushi,salmone,edamame,gomma wakame,carota giapponese,avocato,salsa avocato, furikake,uova di pesce,cipolla fritta',
                'price' => 10.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 7,
            ],
            [
                'name' => 'Tonno poke',
                'image' => 'poke.jpg',
                'description' => 'Riso sushi,tonno,surimi,barbietola rossa,mais,cetriolo,wasabi mayo, furikake,sesamo,cipollotti.',
                'price' => 10.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 7,
            ],
            [
                'name' => 'Gamberi poke',
                'image' => 'poke.jpg',
                'description' => 'Riso sushi,gamberetti,mango,carota,cetriolo,carota giapponese,sesamo salsa,cipollotti,cocco grattugiato,sesamo.',
                'price' => 10.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 7,
            ],
            [
                'name' => 'Tofu poke',
                'image' => 'poke.jpg',
                'description' => 'Riso sushi,tofu,barbietola rossa,carote,gomma wakame,mais,sesamo,sesamo salsa,cipollotti,peperoncino,alglio fritto.',
                'price' => 10.90,
                'visible' => 1,
                'vegan' => 1,
                'spicy' => 1,
                'user_id' => 7,
            ],
            [
                'name' => 'Pollo poke',
                'image' => 'poke.jpg',
                'description' => 'Riso sushi,pollo,edamame,mais,cetriolo,carota giapponese,sriracha mayo, peperoncino,cipolla fritta,sesamo.',
                'price' => 10.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 7,
            ],
            [
                'name' => 'Gym poke',
                'image' => 'poke.jpg',
                'description' => 'Riso bianco,pollo,uova,cetriolo,carote,avocato,salsa di soia,furikake,sesamo,uova di pesce.',
                'price' => 10.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 7,
            ],
            [
                'name' => 'Green poke',
                'image' => 'poke.jpg',
                'description' => 'Riso sushi,salmone,pomodorini,mango,cetriolo,gomma wakame,salsa mango,furikake,cipollotti,cipolle fritte',
                'price' => 10.90,
                'visible' => 1,
                'vegan' => 1,
                'spicy' => 0,
                'user_id' => 7,
            ],
            [
                'name' => 'Hot poke',
                'image' => 'poke.jpg',
                'description' => 'Riso sushi,tonno,gomma wakame,cavolo rosso,carote,surimi,salsa sriracha,peperoncino,uova di pesce,cipolla fritta',
                'price' => 10.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 7,
            ],
            [
                'name' => 'Vaniglia mandorle pralinate e salsa d\'arancio vegano',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Cioccolato',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Crema',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Zabaione',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Fragola',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Stracciatella',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Gianduia',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Pistacchio',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Cremino di nocciola e salsa al cioccolato',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Crema di biscotto dulce de leche e rami al cioccolato',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Pistacchio salato, mandorle e nocciole pralinate',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Nocciola vegana',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 1,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Cheesecake alla fragola',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Crema al caramello, amaretti di saronno e biscotti al cacao',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Mandorla vegana',
                'image' => 'gelato.jpg',
                'description' => 'Vaschetta da 150g',
                'price' => 4.90,
                'visible' => 1,
                'vegan' => 1,
                'spicy' => 0,
                'user_id' => 8,
            ],
            [
                'name' => 'Ravioli di verdure al vapore',
                'image' => 'ravioli.jpg',
                'description' => '',
                'price' => 4.20,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Ravioli di verdure alla griglia',
                'image' => 'ravioli.jpg',
                'description' => '',
                'price' => 4.20,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Ravioli di carne al vapore',
                'image' => 'ravioli.jpg',
                'description' => '',
                'price' => 4.20,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Ravioli di carne alla griglia',
                'image' => 'ravioli.jpg',
                'description' => '',
                'price' => 4.20,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Ravioli di gamberi al vapore',
                'image' => 'ravioli.jpg',
                'description' => '',
                'price' => 4.20,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Ravioli di gamberi alla griglia',
                'image' => 'ravioli.jpg',
                'description' => '',
                'price' => 4.20,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Riso cantonese',
                'image' => 'riso.jpg',
                'description' => '',
                'price' => 5.20,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Riso con ananas e pinoli',
                'image' => 'riso.jpg',
                'description' => '',
                'price' => 5.20,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Riso con verdure',
                'image' => 'riso.jpg',
                'description' => '',
                'price' => 5.20,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Riso con verdure e gamberi',
                'image' => 'riso.jpg',
                'description' => '',
                'price' => 5.20,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Pollo con mandorle',
                'image' => 'anatra.jpg',
                'description' => '',
                'price' => 6.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Pollo con gamberi e funghi',
                'image' => 'anatra.jpg',
                'description' => '',
                'price' => 6.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Pollo in salsa agrodolce',
                'image' => 'anatra.jpg',
                'description' => '',
                'price' => 6.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Anatra alla piastra',
                'image' => 'anatra.jpg',
                'description' => '',
                'price' => 6.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Anatra alla cantonese',
                'image' => 'anatra.jpg',
                'description' => '',
                'price' => 6.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'Anatra alla cantonese',
                'image' => 'anatra.jpg',
                'description' => '',
                'price' => 6.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 9,
            ],
            [
                'name' => 'La Bowl de Oslo',
                'image' => 'bowl.jpg',
                'description' => 'Bowls de Salmone',
                'price' => 10.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 10,
            ],
            [
                'name' => 'La Bowl de Rio',
                'image' => 'bowl.jpg',
                'description' => 'Bowls de Pollo',
                'price' => 10.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 10,
            ],
            [
                'name' => 'La Bowl de Denver',
                'image' => 'bowl.jpg',
                'description' => 'Bowls de Pulled Pork',
                'price' => 10.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 10,
            ],
            [
                'name' => 'La Bowl de Berlino',
                'image' => 'bowl.jpg',
                'description' => 'Bowls Italianas',
                'price' => 10.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 10,
            ],
            [
                'name' => 'La Bowl de Helsinki',
                'image' => 'bowl.jpg',
                'description' => 'Bowls de Tonno',
                'price' => 10.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 10,
            ],
            [
                'name' => 'La Bowl de Tokyo',
                'image' => 'bowl.jpg',
                'description' => 'Bowls Picantes',
                'price' => 10.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 10,
            ],
            [
                'name' => 'La Bowl de Nairobi',
                'image' => 'bowl.jpg',
                'description' => 'Bowls Vegetarianas',
                'price' => 10.30,
                'visible' => 1,
                'vegan' => 1,
                'spicy' => 0,
                'user_id' => 10,
            ],
            [
                'name' => 'El Burrito de Rio',
                'image' => 'burrito.jpg',
                'description' => 'Burritos de Pollo',
                'price' => 9.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 10,
            ],
            [
                'name' => 'El Burrito de Denver',
                'image' => 'burrito.jpg',
                'description' => 'Burritos de Pulled Pork',
                'price' => 9.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 10,
            ],
            [
                'name' => 'El Burrito de Berlino',
                'image' => 'burrito.jpg',
                'description' => 'Burritos Italianos',
                'price' => 9.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 10,
            ],
            [
                'name' => 'El Burrito de Helsinki',
                'image' => 'burrito.jpg',
                'description' => 'Burritos de tonno',
                'price' => 9.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 10,
            ],
            [
                'name' => 'El Burrito de Oslo',
                'image' => 'burrito.jpg',
                'description' => 'Burritos de Salmone',
                'price' => 9.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 10,
            ],
            [
                'name' => 'El Burrito de Tokyo',
                'image' => 'burrito.jpg',
                'description' => 'Burritos Picantes',
                'price' => 9.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 10,
            ],
            [
                'name' => 'Tacos Snack',
                'image' => 'tacos.jpg',
                'description' => 'Tacos Guacamole Picantes',
                'price' => 7.30,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 10,
            ],
            [
                'name' => 'Samosa',
                'image' => 'samosa.jpg',
                'description' => 'Sfoglia Ripiena Di Patate e Piselli Accompagnato Con Masala',
                'price' => 4,
                'visible' => 1,
                'vegan' => 1,
                'spicy' => 0,
                'user_id' => 11,
            ],
            [
                'name' => 'Chicken pakora',
                'image' => 'chickenpakora.jpg',
                'description' => 'Delizioso Petto Di Pollo Fritto Con Farina Di Ceci',
                'price' => 6,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 11,
            ],
            [
                'name' => 'Pakora',
                'image' => 'pakora.jpg',
                'description' => 'Verdure Miste In Pastella Con Farina Di Ceci',
                'price' => 4,
                'visible' => 1,
                'vegan' => 1,
                'spicy' => 0,
                'user_id' => 11,
            ],
            [
                'name' => 'Chicken Tandoori',
                'image' => 'chickentandoori.jpg',
                'description' => 'Popolare piatto della cucina indiana a base di pollo arrosto, yogurt e spezie',
                'price' => 10,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 11,
            ],
            [
                'name' => 'Hariyali Tikka',
                'image' => 'hariyalitikka.jpg',
                'description' => 'Popolare piatto della cucina indiana a base di pollo arrosto, ghee e salsa chutney di coriandolo verde e tamarindo',
                'price' => 12,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 11,
            ],
            [
                'name' => 'Pakora di gamberetti',
                'image' => 'pakoradigamberetti.jpg',
                'description' => 'Delicata frittura di gamberetti',
                'price' => 6,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 11,
            ],
            [
                'name' => 'Tandoori mix',
                'image' => 'tandoorimix.jpg',
                'description' => 'Bocconcini di pollo misti cotto al forno',
                'price' => 15,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 11,
            ],
            [
                'name' => 'Chiken Shahi',
                'image' => 'chickenshahi.jpg',
                'description' => 'Bocconcini di pollo con salsa di panna e anacardi',
                'price' => 12,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 11,
            ],
            [
                'name' => 'Madras Shrimps',
                'image' => 'madrasshrimps.jpg',
                'description' => 'Gamberetti saltati con pomodoro, semi di mostarda e foglie di curry',
                'price' => 14,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 11,
            ],
            [
                'name' => 'Bombay Bonda',
                'image' => 'bombaybonda.jpg',
                'description' => 'Patate macinate pastellate con farina di ceci e fritto',
                'price' => 6,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 11,
            ],
            [
                'name' => 'Lamb Achari',
                'image' => 'lambachari.jpg',
                'description' => 'Bocconcini di agnello cotti con pickle e salsa curry',
                'price' => 11,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 1,
                'user_id' => 11,
            ],
            [
                'name' => 'Lamb Kadai Masala',
                'image' => 'lambkadaimasala.jpg',
                'description' => 'Agnello cotto con pomodoro, cipolla, peperoni e salsa curry',
                'price' => 15,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 11,
            ],
            [
                'name' => 'Onian Bhaji',
                'image' => 'onianbhaji.jpg',
                'description' => 'Anelli di cipolla marinate con farina di ceci e fritti.',
                'price' => 4,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 11,
            ],
            [
                'name' => 'Pastrami MEDIUM”',
                'image' => 'steack.jpg',
                'description' => 'Puro Black Angus USA nel Pan de Cristal “di Barcellona',
                'price' => 10,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 12,
            ],  
            [
                'name' => 'Pastrami LARGE”',
                'image' => 'steack.jpg',
                'description' => 'Puro Black Angus USA nel Pan de Cristal “di Barcellona',
                'price' => 15,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 12,
            ],  
            [
                'name' => 'Black Bao”',
                'image' => 'deluxesteack.jpg',
                'description' => 'Bistecca condita con Pluma di Pata Negra e salsa tonkatsu',
                'price' => 12,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 12,
            ],  
            [
                'name' => 'Fiori saporiti”',
                'image' => 'fioridizucca.jpg',
                'description' => 'Fiori di zucchine con stracciatella e acciughe cantabriche',
                'price' => 10,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 12,
            ],  
            [
                'name' => 'Midollo raffinato”',
                'image' => 'midollo.jpg',
                'description' => 'Midollo di bue con pane caldo',
                'price' => 17,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 12,
            ],  
            [
                'name' => 'Gran Crudo”',
                'image' => 'tartaredifassona.jpg',
                'description' => '10 piccole tartare di Fassona Piemontese, con vari condimenti',
                'price' => 32,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 12,
            ],  
            [
                'name' => 'Japan Piemonte”',
                'image' => 'sashimidivitella.jpg',
                'description' => 'Sashimi di Vitella Piemontese',
                'price' => 12,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 12,
            ],  
            [
                'name' => 'USA Asado”',
                'image' => 'steack.jpg',
                'description' => 'Asado di Black Angus USA Prime',
                'price' => 33,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 12,
            ],  
            [
                'name' => 'Black Angus Steak”',
                'image' => 'deluxesteack.jpg',
                'description' => 'New York Steak di Black Angus USA Prime',
                'price' => 35,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 12,
            ],  
            [
                'name' => 'Big Tomahawk”',
                'image' => 'steack.jpg',
                'description' => 'Tomahawk di Black Angus U.S.A',
                'price' => 60,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 12,
            ],  
            [
                'name' => 'Crocchette perfette”',
                'image' => 'crocchetteperfette.jpg',
                'description' => 'Crocchette basche di jamon iberico “Sagartoki Vitoria” e tartufo nero',
                'price' => 10,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 12,
            ],  
            [
                'name' => 'Pinchos”',
                'image' => 'pinchos.jpg',
                'description' => 'Tre pinchos baschi fatti con sfoglia di patate, uovo con bacon, uovo con chorizo e uovo con tartufo nero “Sagartoki Vitoria”',
                'price' => 14,
                'visible' => 1,
                'vegan' => 0,
                'spicy' => 0,
                'user_id' => 12,
            ],  
        ];

        foreach ($dishes as $dish){
            $newDish = new Dish();
            $newDish->name = $dish['name'];
            $newDish->slug = $newDish->createSlug($newDish->name);
            $newDish->description = $dish['description'];
            $newDish->price = $dish['price'];
            $newDish->visible = $dish['visible'];
            $newDish->vegan = $dish['vegan'];
            $newDish->spicy = $dish['spicy'];
            $newDish->user_id = $dish['user_id'];
            if (!$dish['image']) {
                $newDish->image = $dish['image'];
            } else {
                $newDish->image = 'uploads/'. $dish['image'];
            }
            $newDish->save();
        }
    }
}
